config/routes.rb
Rails.application.routes.draw do

  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}


 scope module: :public do
  root to: 'homes#top'
  post 'customers/sign_in' => 'sessions#create', as: 'customer_session_path'
  get 'about' => 'homes#about', as: 'about'
  get 'item/:id' => 'items#show', as: 'item'
  get 'items' => 'items#index', as: 'items'
  resource :items

  delete 'cart_item/destroy_all' => 'cart_items#destroy_all'
  delete 'cart_items/:id' => 'cart_items#destroy', as: 'cart_items_destroy'
  patch 'cart_items/:id' => 'cart_items#update', as: 'cart_items_update'
  resources :cart_items

  get 'customers/information/edit' => 'customers#edit', as: 'edit_customers'
  get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'customer_unsubscribe'
  patch 'customers/update' => 'customers#update', as: 'customer_update'
  patch 'customers/withdrawal' => 'customers#withdrawal', as: 'customer_withdrawal'
  resource :customers, only: [:show]



  post 'orders/confirm' => 'orders#confirm', as: 'orders_confirm'
  get 'orders/complete' => 'orders#complete', as: 'orders_complete'
  resources :orders

  delete 'addresses/:id' => 'addresses#destroy', as: 'addresses_destroy'
  patch 'addresses/:id' => 'addresses#update', as: 'addresses_update'
  resources :addresses, only: [:index, :edit, :create, :update, :destroy]

 end


 namespace :admin do

  root to: 'homes#top'
  patch 'items/:id' => 'items#update', as: 'update_item'


  resources :items

  get 'customers/:id/edit' => 'customers#edit', as: 'edit_customer'
  patch 'customers/:id' => 'customers#update', as: 'update_customer'
  resources :customers

  resources :orders do
  resources :order_details
 end

end









  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image

  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy

  def with_tax_price
    (price * 1.1).floor
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

def new
  @item = Item.new
end

def create
  item = Item.new(item_params)
  item.save!
  redirect_to admin_item_path(item.id)
end

def index
  @items = Item.page(params[:page]).per(10)
end

def show
  @item = Item.find(params[:id])
end

def edit
    @item = Item.find(params[:id])
end

def update
  item = Item.find(params[:id])
  item.update(item_params)
  redirect_to admin_items_path
end





private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :genre_id, :is_active, :image, :customer_id)
  end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="mt-5 mb-5">
    <headline>商品編集</headline>
   </div>
 </div>
  <div class="row justify-content-center">
    <%= form_with model: @item, url: admin_update_item_path(@item.id) do |f| %>
      <table class="table table-borderless">
    <tr>
  <td>商品画像</td>
<td><%= f.file_field :image, accept: "image/*" %></td>
  </tr>
    <tr>
  <td>商品名</td>
<td><%= f.text_field :name %></td>
  </tr>
    <tr>
  <td>商品説明</td>
<td><%= f.text_area :introduction, :size => "30x5"%></td>
  </tr>
    <tr>
  <td>ジャンル</td>
<td><%= f.select :genre_id, {'ケーキ': 1, 'プリン': 2,'焼き菓子': 3, 'キャンディ': 4}, { include_blank: '--選択してください--'}, { required: true } %></td>
  </tr>
    <tr>
  <td>税抜価格</td>
<td><%= f.text_field :price, :placeholder => "1000" %>円</td>
  </tr>
   <tr>
<td>販売ステータス</td>
  <td>
    <% @item.is_active %>
  <%= f.radio_button :is_active, :true %>
    販売中
      <%= f.radio_button :is_active, :false %>
    販売停止中
  </td>
    </tr>
      </div>
        </table>
      <div class="text-center">
    <%= f.submit "変更を保存", class: "btn btn-lg btn-success"  %>
  </div>
    <% end %>
      </div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<script>
$(function(){
  $('.dropdown-menu .dropdown-item').click(function(){
    var visibleItem = $('.dropdown-toggle', $(this).closest('.dropdown'));
    visibleItem.text($(this).attr('value'));
  });
});
</script>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 px-auto">
  <div class="mt-3 mb-5">
  <headline>商品一覧</headline>
</div>
<%= link_to "新規登録", new_admin_item_path %>
</div>
<table class="table"align="center">
  <thead>
    <tr bgcolor="#f5f5f5">
  <th>商品ID</th><th>商品名</th>
  <th>税抜価格</th><th>ジャンル</th><th>ステータス</th>
    </tr>
  </thead>
  <tbody>
<% @items.each do |item| %>
<tr>
  <td><%= item.id %></td>
    <td><%= link_to item.name, admin_item_path(item) %></td>
    <td><%= item.price %></td>
  <td><%= item.genre_id %></td>
<td>
<% if item.is_active %>
  <p>販売中</p>
  <% else %>
  <p>販売停止中</p>
<% end %>
</td>
</tr>
<% end %>
  </tbody>
</table>
  </div>
<%= paginate @items %>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="mt-5 mb-5">
    <headline>商品新規登録</headline>
   </div>
 </div>
 <div class="row justify-content-center">
  <%= form_with model: @item, url: admin_items_path, method: :post do |f| %>
<table class="table table-borderless">
  <tr>
    <td>商品画像</td>
     <td><%= f.file_field :image, accept: "image/*" %></td>
    </tr>
   <tr>
<td>商品名</td>
  <td><%= f.text_field :name %></td>
   </tr>
     <tr>
      <td>商品説明</td>
    <td><%= f.text_area :introduction, :size => "30x5"%></td>
   </tr>
  <tr>
<td>ジャンル</td>
  <td><%= f.select :genre_id, {'ケーキ': 1, 'プリン': 2,'焼き菓子': 3, 'キャンディ': 4}, { include_blank: '--選択してください--'}, { required: true } %></td>
   </tr>
    <tr>
     <td>税抜価格</td>
    <td><%= f.text_field :price, :placeholder => "1000" %>円</td>
   </tr>
  <tr>
<td>販売ステータス</td>
  <td><%= f.radio_button :is_active, :true %>
    <label>販売中</label>
      <%= f.radio_button :is_active, :false %>
    <label>販売停止中</label>
   </td>
  </tr>
</table>
 <div class="text-center">
  <%= f.submit "新規登録", class: "btn btn-success btn-lg" %>
   </div>
    </div>
   </div>


<% end %>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<script>
$(function(){
  $('.dropdown-menu .dropdown-item').click(function(){
    var visibleItem = $('.dropdown-toggle', $(this).closest('.dropdown'));
    visibleItem.text($(this).attr('value'));
  });
});
</script>

app/views/admin/items/show.html.erb
<div class="container">
  <div class="m-5">
  <headline>商品詳細</headline>
  </div>
  </div>
 </div>
  <div class="row justify-content-center">
    <div class="col-3">
  <% if @item.image.attached? %>
    <%= image_tag @item.image, size: "300x250" %>
  <% else %>
    <%= image_tag 'no_image', size: "200x200" %>
  <% end %>
   </div>
  <div class="col-5">
<table class="table table-borderless">
<tr>
  <td>商品名</td>
  <td><%= @item.name %></td>
</tr>
<tr>
  <td>商品説明</td>
  <td><%= @item.introduction %></td>
</tr>
<tr>
  <td>ジャンル</td>
  <td><%= @item.genre_id %></td>
</tr>
<tr>
   <td>税抜価格</td>
   <td><%= @item.price %>
  (<%= @item.with_tax_price %>円)</td>
</tr>
<tr>
  <td>販売ステータス</td>
  <td>
  <% if @item.is_active == true %>
  販売中
  <% else %>
  販売停止中
  <% end %>
  </td>
</tr>
</table>
  </div>
  </div>
  <div class="text-center">
  <%= link_to "編集する", edit_admin_item_path(@item), class: "btn btn-lg btn-success"  %>
  </div>
</div>