config/routes.rb
Rails.application.routes.draw do

  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}


 scope module: :public do
  root to: 'homes#top'
  post 'customers/sign_in' => 'sessions#create', as: 'customer_session_path'
  get 'about' => 'homes#about', as: 'about'
  get 'item/:id' => 'items#show', as: 'item'
  get 'items' => 'items#index', as: 'items'
  resource :items

  delete 'cart_item/destroy_all' => 'cart_items#destroy_all'
  delete 'cart_items/:id' => 'cart_items#destroy', as: 'cart_items_destroy'
  patch 'cart_items/:id' => 'cart_items#update', as: 'cart_items_update'
  resources :cart_items

  get 'customers/information/edit' => 'customers#edit', as: 'edit_customers'
  get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'customer_unsubscribe'
  patch 'customers/update' => 'customers#update', as: 'customer_update'
  patch 'customers/withdrawal' => 'customers#withdrawal', as: 'customer_withdrawal'
  resource :customers, only: [:show]



  post 'orders/confirm' => 'orders#confirm', as: 'orders_confirm'
  get 'orders/complete' => 'orders#complete', as: 'orders_complete'
  resources :orders

  delete 'addresses/:id' => 'addresses#destroy', as: 'addresses_destroy'
  patch 'addresses/:id' => 'addresses#update', as: 'addresses_update'
  resources :addresses, only: [:index, :edit, :create, :update, :destroy]

 end


 namespace :admin do

  root to: 'homes#top'
  patch 'items/:id' => 'items#update', as: 'update_item'


  resources :items

  get 'customers/:id/edit' => 'customers#edit', as: 'edit_customer'
  patch 'customers/:id' => 'customers#update', as: 'update_customer'
  resources :customers

  resources :orders do
  resources :order_details
 end

end









  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy

  def active_for_authentication?
    super && (is_deleted == false)
  end


  def full_name
    self.last_name + self.first_name
  end

  def full_name_kana
    self.last_name_kana + self.first_name_kana
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

def new
  @customers = Customer.new
end

def create
  customer = Customer.new(item_params)
  customer.save!
  redirect_to customers_information_edit_path(cu)
end

def index
  @customers = Customer.order("created_at DESC").page(params[:page]).per(10)
end

def show
  @customer = Customer.find(params[:id])
end

def edit
  @customer = Customer.find(params[:id])
end

def update
  customer = Customer.find(params[:id])
  customer.update(customer_params)
  redirect_to admin_customer_path(customer.id)
end




private

  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :last_name_kana, :first_name_kana, :email, :postal_code,:address, :telephon_number, :is_deleted )
  end

end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row">
   <div class="mt-3 mb-5">
  <headline><%= @customer.full_name %>さんの会員情報編集</headline>
   </div>
  </div>
</div>
<%= form_with model: @customer, url: admin_customer_path(@customer) do |f| %>
<div class="container">
  <div class="row">
    <table class="table table-borderless">
     <tr>
    <td>会員ID</td>
  <td><%= @customer.id %></td>
    </tr>
      <tr>
    <td>氏名</td>
  <td><%= f.text_field :last_name %>
    <%= f.text_field :first_name %></td>
      </tr>
      <tr>
    <td>フリガナ</td>
  <td><%= f.text_field :last_name_kana %>
    <%= f.text_field :first_name_kana %></td>
      </tr>
     <tr>
  <td>郵便番号</td>
    <td><%= f.text_field :postal_code %></td>
      </tr>
      <tr>
    <td>住所</td>
  <td><%= f.text_field :address, class: "w-75" %></td>
      </tr>
     <tr>
   <td>電話番号</td>
 <td><%= f.text_field :telephone_number %></td>
   </tr>
   <tr>
 <td>メールアドレス</td>
    <td><%= f.text_field :email %></td>
      </tr>
      <tr>
     <td>会員ステータス</td>
   <td>
 <%= f.radio_button :is_deleted, :true %>
  有効
  <%= f.radio_button :is_deleted, :false %>
  退会
   </td>
     </tr>
      </table>
      <%= f.submit "変更を保存", class: "btn btn-lg btn-success mx-auto"  %>
     <% end %>
   </div>
 </div>

app/views/admin/customers/index.html.erb
<div class="container">
    <div class="row">
       <div class="mt-3 mb-3">
        <headline>会員一覧</headline>
       </div>
    <table class="table" align="center">
  <thead>
    <tr bgcolor="#f5f5f5">
      <th>会員ID</th><th>氏名</th>
        <th>メールアドレス</th><th>ステータス</th>
    </tr>
  </thead>
<tbody>
  <% @customers.each do |customer| %>
  <tr>
    <td><%= customer.id %></td>
      <td><%= link_to customer.full_name, admin_customer_path(customer) %></td>
        <td><%= customer.email %></td>
      <td>
    <% if customer.is_deleted == false %>
  有効
<% else %>
  退会
    <% end %>
      </td>
    </tr>
  <% end %>
</tbody>
    </table>
    </div>
    <%= paginate @customers %>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
   <div class="mt-3 mb-3">
    <headline><%= @customer.full_name %>さんの会員詳細</headline>
   </div>
  </div>
  </div>
  <div class="container">
 <div class="text-justify">
<table class="table w-50 mb-5 table-borderless">
<tr>
  <td scope="col" style="width: 30%">会員ID</td>
   <td scope="col" style="width: 70%">
    <%= @customer.id %>
  </td>
</tr>
<tr>
  <td>氏名</td>
  <td><%= @customer.full_name %></td>
</tr>
<tr>
  <td>カナ</td>
   <td><%= @customer.full_name_kana %></td>
</tr>
<tr>
  <td>郵便番号</td>
   <td><%= @customer.postal_code %></td>
</tr>
<tr>
  <td>住所</td>
   <td><%= @customer.address %></td>
</tr>
<tr>
  <td>電話番号</td>
   <td><%= @customer.telephone_number %></td>
</tr>
<tr>
  <td>メールアドレス</td>
   <td><%= @customer.email %></td>
</tr>
<tr>
  <td>会員ステータス</td>
  <td><% if @customer.is_deleted == false %>
  有効
<% else %>
  退会
    <% end %></td>
</tr>
</table>
  <div class="p-2 mt-5 ml-3">
    <%= link_to "編集する", admin_edit_customer_path(@customer), class: "btn btn-success btn-sm" %>
  </div>
 </div>
  <div class="p-2 mt-3">
    <%= link_to "注文履歴一覧を見る", admin_root_path, class: "btn btn-primary btn-sm" %>
  </div>
</div>