config/routes.rb
Rails.application.routes.draw do

  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}


 scope module: :public do
  root to: 'homes#top'
  post 'customers/sign_in' => 'sessions#create', as: 'customer_session_path'
  get 'about' => 'homes#about', as: 'about'
  get 'item/:id' => 'items#show', as: 'item'
  get 'items' => 'items#index', as: 'items'
  resource :items

  delete 'cart_item/destroy_all' => 'cart_items#destroy_all'
  delete 'cart_items/:id' => 'cart_items#destroy', as: 'cart_items_destroy'
  patch 'cart_items/:id' => 'cart_items#update', as: 'cart_items_update'
  resources :cart_items

  get 'customers/information/edit' => 'customers#edit', as: 'edit_customers'
  get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'customer_unsubscribe'
  patch 'customers/update' => 'customers#update', as: 'customer_update'
  patch 'customers/withdrawal' => 'customers#withdrawal', as: 'customer_withdrawal'
  resource :customers, only: [:show]



  post 'orders/confirm' => 'orders#confirm', as: 'orders_confirm'
  get 'orders/complete' => 'orders#complete', as: 'orders_complete'
  resources :orders

  delete 'addresses/:id' => 'addresses#destroy', as: 'addresses_destroy'
  patch 'addresses/:id' => 'addresses#update', as: 'addresses_update'
  resources :addresses, only: [:index, :edit, :create, :update, :destroy]

 end


 namespace :admin do

  root to: 'homes#top'
  patch 'items/:id' => 'items#update', as: 'update_item'


  resources :items

  get 'customers/:id/edit' => 'customers#edit', as: 'edit_customer'
  patch 'customers/:id' => 'customers#update', as: 'update_customer'
  resources :customers

  resources :orders do
  resources :order_details
 end

end









  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/order.rb
class Order < ApplicationRecord

  enum payment_method: { credit_card: 0, transfer: 1 }

  enum status: { waiting_for_payment: 0, payment_confirmation: 1, in_production: 2, preparing_to_ship: 3, sent: 4 }

  belongs_to :customer
  has_many :order_details, dependent: :destroy
  has_many :addresses, dependent: :destroy

  def address_display
  "〒" + postal_code + " " + address + " " + name
  end

  def full_name
    self.last_name + self.first_name
  end

  def full_name_kana
    self.last_name_kana + self.first_name_kana
  end

  def subtotal
    item.with_tax_price * amount
  end


end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    @total = 0
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    if @order.status == "payment_confirmation"
       @order.order_details.each do |order_detail|
         order_detail.update(making_status:1)
    end
    end
    redirect_to admin_order_path
  end

  def order_params
    params.require(:order).permit(:customer_id, :item_id, :tax_included_price, :amount, :making_status, :payment_method, :status )
  end

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="mt-5 mb-5">
    <headline>注文履歴詳細</headline>
  </div>
<div class="row">
  <div class="col-2">
    <div class="h5 font-weight-bold">購入者</div>
  </div>
<div class="col-8">
  <%=  link_to admin_root_path do %>
    <%= @order.customer.full_name %>
  <% end %>
  </div>
</div>
<div class="row">
  <div class="col-2">
    <div class="h5 font-weight-bold">注文日</div>
  </div>
  <div class="col-8">
    <%= @order.created_at.strftime('%Y/%m/%d') %>
  </div>
</div>
<div class="row">
  <div class="col-2">
    <div class="h5 font-weight-bold">配送先</div>
  </div>
  <div class="col-8">
    〒<%= @order.postal_code %>
    <%= @order.address %>
    <p><%= @order.name %></p>
  </div>
</div>
<div class="row">
  <div class="col-2">
    <div class="h5 font-weight-bold">支払方法</div>
  </div>
  <div class="col-8">
    <%= @order.payment_method_i18n %>
  </div>
</div>
<div class="row">
  <div class="col-2">
    <div class="h5 font-weight-bold">注文ステータス</div>
  </div>
  <div class="col-8">
    <%= form_with model: @order, url: admin_order_path do |f| %>
    <%= f.select :status, Order.statuses.keys.map {|k| [I18n.t("enums.order.status.#{k}"), k]} %>
<%= f.submit "更新", class:"btn btn-sm btn-success" %>
<% end %>
  </div>
</div>
<div class="row">
<table class=" col-md-8 table table-sm w-75 mt-5">
  <tr bgcolor="#f5f5f5">
    <th>商品名</th><th>単価(税込)</th>
    <td>数量</td><td>小計</td><td>制作ステータス</td>
  </tr>
  <% @order_details.each do |order_detail| %>
    <%= form_with model: order_detail, url: admin_order_order_detail_path(@order,order_detail) do |f| %>
    <tr>
      <td><%= order_detail.item.name %></td>
        <td><%= order_detail.item.with_tax_price %></td>
          <td><%= order_detail.amount %></td>
        <td><%= order_detail.item.with_tax_price*order_detail.amount %></td>
      <td><%= f.select :making_status, OrderDetail.making_statuses.keys.map {|k| [I18n.t("enums.order_detail.making_status.#{k}"), k]} %>
      <%= f.submit "更新", class: "btn　btn-sm btn-success" %></td>
    </tr>
  <% end %>
  <% end %>
</table>
  <div class="col-md-3 offset-md-1 mt-5">
    <table>
      <tr>
        <th class="h5 font-weight-bold">商品合計</th>
          <td class="pl-2"><%= @order.amount - @order.postage %>円</td>
      </tr>
      <tr>
        <th class="h5 font-weight-bold">送料</th>
          <td class="pl-2"><%= @order.postage %>円</td>
      </tr>
      <tr>
        <th class="h5 font-weight-bold">請求金額合計</th>
          <td class="pl-2"><%= @order.amount %>円</td>
      </tr>
    </table>
  </div>
  </div>
</div>