config/routes.rb
Rails.application.routes.draw do

  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}


 scope module: :public do
  root to: 'homes#top'
  post 'customers/sign_in' => 'sessions#create', as: 'customer_session_path'
  get 'about' => 'homes#about', as: 'about'
  get 'item/:id' => 'items#show', as: 'item'
  get 'items' => 'items#index', as: 'items'
  resource :items

  delete 'cart_item/destroy_all' => 'cart_items#destroy_all'
  delete 'cart_items/:id' => 'cart_items#destroy', as: 'cart_items_destroy'
  patch 'cart_items/:id' => 'cart_items#update', as: 'cart_items_update'
  resources :cart_items

  get 'customers/information/edit' => 'customers#edit', as: 'edit_customers'
  get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'customer_unsubscribe'
  patch 'customers/update' => 'customers#update', as: 'customer_update'
  patch 'customers/withdrawal' => 'customers#withdrawal', as: 'customer_withdrawal'
  resource :customers, only: [:show]



  post 'orders/confirm' => 'orders#confirm', as: 'orders_confirm'
  get 'orders/complete' => 'orders#complete', as: 'orders_complete'
  resources :orders

  delete 'addresses/:id' => 'addresses#destroy', as: 'addresses_destroy'
  patch 'addresses/:id' => 'addresses#update', as: 'addresses_update'
  resources :addresses, only: [:index, :edit, :create, :update, :destroy]

 end


 namespace :admin do

  root to: 'homes#top'
  patch 'items/:id' => 'items#update', as: 'update_item'


  resources :items

  get 'customers/:id/edit' => 'customers#edit', as: 'edit_customer'
  patch 'customers/:id' => 'customers#update', as: 'update_customer'
  resources :customers

  resources :orders do
  resources :order_details
 end

end









  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

  def address_display
  '〒' + postal_code + ' ' + receiver_address + ' ' + name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def full_name
    self.last_name + self.first_name
  end

  def full_name_kana
    self.last_name_kana + self.first_name_kana
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :item
  belongs_to :customer

  def subtotal
    item.with_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy

  def active_for_authentication?
    super && (is_deleted == false)
  end


  def full_name
    self.last_name + self.first_name
  end

  def full_name_kana
    self.last_name_kana + self.first_name_kana
  end

end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image

  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy

  def with_tax_price
    (price * 1.1).floor
  end

end

app/models/order.rb
class Order < ApplicationRecord

  enum payment_method: { credit_card: 0, transfer: 1 }

  enum status: { waiting_for_payment: 0, payment_confirmation: 1, in_production: 2, preparing_to_ship: 3, sent: 4 }

  belongs_to :customer
  has_many :order_details, dependent: :destroy
  has_many :addresses, dependent: :destroy

  def address_display
  "〒" + postal_code + " " + address + " " + name
  end

  def full_name
    self.last_name + self.first_name
  end

  def full_name_kana
    self.last_name_kana + self.first_name_kana
  end

  def subtotal
    item.with_tax_price * amount
  end


end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  enum making_status: { cannot_started: 0, waiting_production: 1, making: 2, complete: 3 }


  belongs_to :order
  belongs_to :item

  def with_tax_price
    (price * 1.1).floor
  end

  def subtotal
    item.with_tax_price * amount
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  def top
    @orders = Order.order("created_at DESC").page(params[:page]).per(10)
    @orders = Order.page(params[:page]).per(10)
  end



private

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

def new
  @item = Item.new
end

def create
  item = Item.new(item_params)
  item.save!
  redirect_to admin_item_path(item.id)
end

def index
  @items = Item.page(params[:page]).per(10)
end

def show
  @item = Item.find(params[:id])
end

def edit
    @item = Item.find(params[:id])
end

def update
  item = Item.find(params[:id])
  item.update(item_params)
  redirect_to admin_items_path
end





private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :genre_id, :is_active, :image, :customer_id)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    @total = 0
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    if @order.status == "payment_confirmation"
       @order.order_details.each do |order_detail|
         order_detail.update(making_status:1)
    end
    end
    redirect_to admin_order_path
  end

  def order_params
    params.require(:order).permit(:customer_id, :item_id, :tax_included_price, :amount, :making_status, :payment_method, :status )
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)

    if customer_signed_in?
        customers_path
    elsif admin_signed_in?
        admin_root_path
    else
        new_admin_session_path
    end

  end


  def after_sign_out_path_for(resources)

    if resources == :customer
        root_path
    elsif resources == :admin
        new_admin_session_path
    else
        admin_root_path

    end

  end



  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name,
    :first_name_kana, :last_name_kana, :email, :address, :postal_code, :telephone_number])

    devise_parameter_sanitizer.permit(:sign_in, keys: [:email])

  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/admin/custmers_helper.rb
module Admin::CustmersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>NaganoCake</title>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
<header>
  <div class="border-bottom border-dark" style="padding:10px;">
    <div class="container">
      <div class="row">
        <div class="col-4">
      <%= link_to "ながのCAKE", root_path, class: "font-weight-bold text-info h1 text-decoration-none" %>
    </div>
    <div class="col-8">
  <div class="text-right">

<% if admin_signed_in? %>
<div class="btn-group">
<%= link_to "商品一覧", admin_items_path, class: "btn btn-outline-secondary mr-3" %>
<%= link_to "会員一覧", admin_customers_path, class: "btn btn-outline-secondary mr-3" %>
<%= link_to "注文履歴一覧", admin_root_path, class: "btn btn-outline-secondary mr-3" %>
<%= link_to "ジャンル一覧", admin_root_path, class: "btn btn-outline-secondary mr-3" %>
<%= button_to 'ログアウト', destroy_admin_session_path, method: :delete, class:"btn btn-outline-secondary" %>
</div>
<% elsif customer_signed_in? %>

ようこそ、<%= current_customer.last_name %>さん！
<div class="btn-group">
<%= link_to "マイページ", customers_path, class: "btn btn-outline-secondary mr-3" %>
<%= link_to "商品一覧", items_path, class: "btn btn-outline-secondary mr-3" %>
<%= link_to "カート", cart_items_path, class: "btn btn-outline-secondary mr-3" %>
<%= button_to 'ログアウト', destroy_customer_session_path, method: :delete, class:"btn btn-outline-secondary" %>
</div>
<% else %>
<div class="btn-group">
<%= link_to "About", about_path, class: "btn btn-outline-secondary" %>
<%= link_to "商品一覧", items_path, class: "btn btn-outline-secondary" %>
<%= link_to "新規登録", new_customer_registration_path, class: "btn btn-outline-secondary" %>
<%= link_to "ログイン", new_customer_session_path, class: "btn btn-outline-secondary" %>
</div>
<% end %>
</div>
<div class="input-group">
  <input type="text" id="txt-search" class="form-control mt-3" placeholder="Search"></input>
  <span class="input-group-btn input-group-append">
    <submit type="submit" id="btn-search" class="btn btn-primary mt-3"><i class="fas fa-search"></i></submit>
    </div>
  </span>
  </div>
    </div>
  </div>
</header>
  <body>
    <%= yield %>
  </body>
    <footer>
    </footer>
</html>